server:
  port: 50000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:./demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false

shortenUrl:
  # time to live (in minutes)
  timeToLive: 30
  scheduledTask:
    # Cron Expression (Spring Scheduling format)
    # Execute every 30min.
    cronExpression: "0 */30 * * * *"
